# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers



    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mv .env.ci .env
      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
  deploy:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - add_ssh_key:
          fingerprints:
            - "d1:dd:d4:56:00:41:a8:9e:d2:88:8f:e0:a0:56:9d:df"

      - run:
          name: Ma premiere connexion a ma vm
          command: |
            ssh azureuser@51.103.64.4
            exit
workflow:
  version: 2
  notify_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
         requires:
           - build
         filters:
           branches:
             only:
               - main





